steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-t',
      'gcr.io/vairav26082023/inoxx:1.0',
      '.'
    ]
    dir: web4

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/vairav26082023/inoxx:1.0']

  - name: 'gcr.io/cloud-builders/kubectl'
    args: ['apply', '-f', 'k8s/']
    env:
      - 'CLOUDSDK_COMPUTE_ZONE=us-central1-c'
      - 'CLOUDSDK_CONTAINER_CLUSTER=web4'

  - name: 'gcr.io/cloud-builders/kubectl'
    args: [
      'set',
      'image',
      'deployment',
      'web4',
      'web4=gcr.io/vairav26082023/inoxx:1.0'
    ]
    env:
      - 'CLOUDSDK_COMPUTE_ZONE=us-central1-c'
      - 'CLOUDSDK_CONTAINER_CLUSTER=web4'
images:
  - 'gcr.io/vairav26082023/inoxx:1.0'
