apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ix-web
  namespace: argocd
spec:
  project: default


source:
  repourl: https://github.com/Vairavmoorthy/gcp-cicd.git
  targetRevison: HEAD
  path: K8S
destination: 
   server: https://kubernetes.default.svc
   namespace: argocd

syncPolicy: 
  syncOptions:    
  - CreateNamespace=true

  automated:
   selfHeal: true
   
